import Head from "next/head";
import { Main } from "../src/components/Main";
import { useEffect, useState } from "react";
import TargetSVG from "../src/components/TargetSVG";
import CoolBg from "../src/components/CoolBg";

export default function Home() {
  const [loaded, setLoaded] = useState(false);
  // const mouseMove = (e: any) => {
  //   const X = e.clientX - 450;
  //   const Y = e.clientY - 450;
  //   const el = document.getElementById("target");
  //   if (el) el.style.transform = `translate3d(${-X / 7}px, ${-(Y / 7)}px, 0px)`;
  // };

  // useEffect(() => {
  //   window.addEventListener("mousemove", mouseMove);
  //   return () => {
  //     window.removeEventListener("mousemove", mouseMove);
  //   };
  // });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="animate-slideup w-[100vw] bg-[#282c34] z-[100] h-[100vh] flex absolute justify-center items-center">
        <div className="inline h-[60vh]">
          <TargetSVG motion={false} rotate={true} />
        </div>
      </div> */}
      <div
        id="scene"
        className={
          "opacity-75 md:pl-[30%] lg:pl-[50%] pl-0 duration-500 h-full w-full inset-0 z-[0] text-right fixed"
        }
      >
        <div data-depth="0.6" className="w-full h-full">
          <TargetSVG motion={true} />
        </div>
      </div>
      <Main />
    </>
  );
}
